export function buildMemoryDomainSystemContext(): string {
  return [
    '## Heddle-Managed Memory Domain',
    '',
    'Heddle-managed memory is the durable recall substrate for the agent. It is different from ordinary repository documentation.',
    '',
    '### Knowledge Surfaces',
    '',
    '- Repository docs such as README files, AGENTS.md, or docs/ are project-authored evidence. Use them for current product, code, and user-facing documentation facts.',
    '- Heddle-managed memory under .heddle/memory is agent-maintained durable context. Use it for preferences, workflows, current-state handoff, operational conventions, relationships, history, and not-obvious knowledge that helps future sessions avoid rediscovery.',
    '- Live workspace evidence wins when implementation facts conflict with memory. Memory is strongest for user/team preferences, recurring workflows, historical context, and operational knowledge that may not be obvious from code.',
    '',
    '### Retrieval Model',
    '',
    '- For preference-shaped, workflow-shaped, planning-style, ticket/format, review-style, coordination, or recurring operational questions, consult Heddle-managed memory before broad repository search.',
    '- Follow the catalog path: read the root memory catalog, then the relevant folder README catalog, then focused notes listed there.',
    '- Use search_memory_notes when the likely folder is unclear. Use list_memory_notes and read_memory_note when the catalog already points to a likely folder or note.',
    '- Do not grep ordinary repo files first for durable preferences or workflow conventions unless memory has no relevant path or live repository evidence is needed.',
    '',
    '### Maintenance Model',
    '',
    '- Preserve the discovery path. Every durable memory note must be discoverable from the root README.md or a folder README.md.',
    '- Prefer updating an existing cataloged note over scattering many small notes.',
    '- Keep folder README.md files as indexes, not long-form dumps.',
    '- Do not store secrets, speculative guesses, one-turn plans, or temporary command output.',
    '',
    '### Checkpoint Model',
    '',
    '- Before the final answer, run a quick memory checkpoint when memory_checkpoint is available.',
    '- Record durable candidates when the user states a future preference/workflow/format or the turn uncovers stable reusable workspace knowledge.',
    '- Skip one-off task details, duplicate facts, temporary plans, speculative guesses, and information that should remain only in the current transcript.',
    '',
  ].join('\n');
}
